#include <stdio.h>
char *skeleton[] = {
"#! /bin/sh",
"# Provides:          rasp4you",
"# Required-Start:    $remote_fs $syslog",
"# Required-Stop:     $remote_fs $syslog",
"# Default-Start:     2 3 4 5",
"# Default-Stop:      0 1 6",
"# Short-Description: Easy access to your Raspberry from everywhere",
"# Description:       This program allow full internet access by domain name at your raspberry",
"#                    sited in a private local area network without router configuration",
"# Author: Cristine Farrel <rasp4you@rasp4you.com>",
"",
"PATH=/sbin:/usr/sbin:/bin:/usr/bin",
"DESC=\"rasp4you\"",
"NAME=rasp4you",
"DAEMON=/usr/sbin/$NAME",
"DAEMON_ARGS=\"--daemonize\"",
"PIDFILE=/var/run/$NAME.pid",
"SCRIPTNAME=/etc/init.d/$NAME",
"",
"[ -x \"$DAEMON\" ] || exit 0",
"",
". /lib/init/vars.sh",
". /lib/lsb/init-functions",
"",
"do_start()",
"{",
"	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null || return 1",
"	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS || return 2",
"}",
"do_stop()",
"{",
"	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME",
"	RETVAL=\"$?\"",
"	rm -f $PIDFILE",
"	return \"$RETVAL\"",
"}",
"#",
"# Function that sends a SIGHUP to the daemon/service",
"#",
"do_reload() {",
"	#",
"	# If the daemon can reload its configuration without",
"	# restarting (for example, when it is sent a SIGHUP),",
"	# then implement that here.",
"	#",
"	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME",
"	return 0",
"}",
"",
"case \"$1\" in",
"  start)",
"	do_start",
"	case \"$?\" in",
"		0) log_daemon_msg \"Started\" $NAME ;;",
"		1) log_daemon_msg \"Already started\" $NAME ;;",
"		2) log_daemon_msg \"Not started\" $NAME ;;",
"	esac",
"	;;",
"  stop)",
"	do_stop",
"	case \"$?\" in",
"		0) log_daemon_msg \"Stopped\" $NAME ;;",
"		1|2) log_daemon_msg \"Already stopped\" $NAME ;;",
"	esac",
"	;;",
"  status)",
"       status_of_proc -p $PIDFILE \"$DAEMON\" \"$NAME\" && exit 0 || exit $?",
"       ;;",
"  restart|force-reload)",
"	do_stop",
"	do_start",
"	case \"$?\" in",
"		0|1) log_daemon_msg \"Restarted\" $NAME ;;",
"		2) log_daemon_msg \"Not restarted\" $NAME ;;",
"	esac",
"	;;",
"  *)",
"	#echo \"Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}\" >&2",
"	echo \"Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}\" >&2",
"	exit 3",
"	;;",
"esac",
"",
":",
NULL };
char *license[] = {
"This software is released under MIT License (MIT)",
"",
"Copyright (c) 2015 Rasp4you",
"",
"Permission is hereby granted, free of charge, to any person obtaining a copy",
"of this software and associated documentation files (the \"Software\"), to deal",
"in the Software without restriction, including without limitation the rights",
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
"copies of the Software, and to permit persons to whom the Software is",
"furnished to do so, subject to the following conditions:",
"",
"The above copyright notice and this permission notice shall be included in all",
"copies or substantial portions of the Software.",
"",
"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR",
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,",
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE",
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER",
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,",
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE",
"SOFTWARE.",
NULL };
